# Start base
FROM alpine:3.17.10

RUN apk add --update --no-cache heirloom-mailx fuse curl

RUN \
    mkdir -p /var/spool/cron/crontabs /var/log; \
    touch /var/log/cron.log;

COPY ./base/backup.sh /bin/backup
COPY ./base/entry.sh /entry.sh
COPY ./base/backup_utils.sh /backup_utils.sh

WORKDIR "/"
ENTRYPOINT ["/entry.sh"]
CMD ["tail","-fn0","/var/log/cron.log"]
# End base


COPY <<EOF /bin/backup_service
#!/bin/sh

echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION" >> "/var/log/backup-last.log"
echo "S3_BUCKET: $S3_BUCKET" >> "/var/log/backup-last.log"

source /backup_utils.sh
FOLDER=$(formatDate "$DATE_FMT").tar.gz

tar -cvzf /tmp/$FOLDER $DIR_NAME

aws s3 cp "/tmp/$FOLDER" "s3://$S3_BUCKET/$FOLDER" >> "/var/log/backup-last.log" 2>&1

rm -rf /tmp/$FOLDER
EOF


RUN apk add --no-cache aws-cli
RUN chmod +x /bin/backup_service
